openapi: 3.0.0
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        status:
          type: number
        message:
          type: string
    PutDocumentRequest:
      type: object
      properties:
        endpoint:
          type: string
    PutDocumentResponse:
      type: object
      properties:
        status:
          type: number
        body:
          type: object
    GetDocumentResponse:
      type: object
      properties:
        status:
          type: number
        body:
          type: object
  securitySchemes: {}
info:
  title: ""
  description: ""
  version: da1ffad1-d650-48a9-8a24-0f2ca89d163c
paths:
  /translate:
    post:
      operationId: addTranslation
      summary: Add translation
      description: Creates a translation for a given endpoint
      responses:
        "200":
          description: The ID of the translation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutDocumentResponse"
  /translate/{id}:
    get:
      operationId: getTranslation
      summary: Get translation
      description: Gets the translation of a given endpoint
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: Response of SW-API translated into Spanish
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetDocumentResponse"
        "400":
          description: An error message when translating an endpoint
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: A not found error message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
