service: sw-translate
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2 
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:664872295309:table/SW_Translation

functions:
  addTranslation:
    handler: src/functions/addTranslation.translate
    events:
      - httpApi:
          path: /translate
          method: post
  getTranslation:
    handler: src/functions/getTranslation.translate
    events:
      - httpApi:
          path: /translate/{id}
          method: get

resources:
  Resources:
    Translation:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SW_Translation
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH