// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "sw-translate",
    "version": "1"
  },
  "paths": {
    "/translate": {
      "post": {
        "summary": "addTranslation",
        "description": "",
        "operationId": "addTranslation.post./translate",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/translate/{id}": {
      "get": {
        "summary": "getTranslation",
        "description": "",
        "operationId": "getTranslation.get./translate/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};